# generated by appcreator
import django_tables2 as tables
from django_tables2.utils import A
from . models import (
    Certainty,
    CollectionSpec,
    Culture,
    Fabric,
    Hardware,
    Illustration,
    IllustrationPanel,
    ImagingTechnique,
    Institution,
    Material,
    Object,
    PaintingStyle,
    PaintingSubTechnique,
    Period,
    Person,
    Place,
    Shape,
    ShapeComponent,
    ThreedData
)


class CertaintyTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')

    class Meta:
        model = Certainty
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class CollectionSpecTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')

    class Meta:
        model = CollectionSpec
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class CultureTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')

    class Meta:
        model = Culture
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class FabricTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')

    class Meta:
        model = Fabric
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class HardwareTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')

    class Meta:
        model = Hardware
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class IllustrationTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    ill_author = tables.ManyToManyColumn()

    class Meta:
        model = Illustration
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class IllustrationPanelTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    illtab_author = tables.ManyToManyColumn()

    class Meta:
        model = IllustrationPanel
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class ImagingTechniqueTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')

    class Meta:
        model = ImagingTechnique
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class InstitutionTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')

    class Meta:
        model = Institution
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class MaterialTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')

    class Meta:
        model = Material
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class ObjectTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    shape = tables.ManyToManyColumn()
    shape_comp = tables.ManyToManyColumn()
    object_associated_to_inv = tables.ManyToManyColumn()
    period = tables.ManyToManyColumn()
    culture = tables.ManyToManyColumn()
    material = tables.ManyToManyColumn()
    material_fabric = tables.ManyToManyColumn()
    painting_style = tables.ManyToManyColumn()
    painting_style_sub = tables.ManyToManyColumn()
    provenance_acquisition = tables.ManyToManyColumn()

    class Meta:
        model = Object
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class PaintingStyleTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')

    class Meta:
        model = PaintingStyle
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class PaintingSubTechniqueTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')

    class Meta:
        model = PaintingSubTechnique
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class PeriodTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')

    class Meta:
        model = Period
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class PersonTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')

    class Meta:
        model = Person
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class PlaceTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    place_type = tables.ManyToManyColumn()

    class Meta:
        model = Place
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class ShapeTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')

    class Meta:
        model = Shape
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class ShapeComponentTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')

    class Meta:
        model = ShapeComponent
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class ThreedDataTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    threed_location = tables.ManyToManyColumn()
    threed_author = tables.ManyToManyColumn()
    threed_merging_author = tables.ManyToManyColumn()
    threed_postproc_author = tables.ManyToManyColumn()
    threed_postproc_low_author = tables.ManyToManyColumn()

    class Meta:
        model = ThreedData
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}
