# generated by appcreator
from django.urls import path

from . import views

app_name = "vases"
urlpatterns = [
    path("certainty/", views.CertaintyListView.as_view(), name="certainty_browse"),
    path(
        "certainty/detail/<int:pk>",
        views.CertaintyDetailView.as_view(),
        name="certainty_detail",
    ),
    path("certainty/create/", views.CertaintyCreate.as_view(), name="certainty_create"),
    path(
        "certainty/edit/<int:pk>",
        views.CertaintyUpdate.as_view(),
        name="certainty_edit",
    ),
    path(
        "certainty/delete/<int:pk>",
        views.CertaintyDelete.as_view(),
        name="certainty_delete",
    ),
    path(
        "collectionspec/",
        views.CollectionSpecListView.as_view(),
        name="collectionspec_browse",
    ),
    path(
        "collectionspec/detail/<int:pk>",
        views.CollectionSpecDetailView.as_view(),
        name="collectionspec_detail",
    ),
    path(
        "collectionspec/create/",
        views.CollectionSpecCreate.as_view(),
        name="collectionspec_create",
    ),
    path(
        "collectionspec/edit/<int:pk>",
        views.CollectionSpecUpdate.as_view(),
        name="collectionspec_edit",
    ),
    path(
        "collectionspec/delete/<int:pk>",
        views.CollectionSpecDelete.as_view(),
        name="collectionspec_delete",
    ),
    path("culture/", views.CultureListView.as_view(), name="culture_browse"),
    path(
        "culture/detail/<int:pk>",
        views.CultureDetailView.as_view(),
        name="culture_detail",
    ),
    path("culture/create/", views.CultureCreate.as_view(), name="culture_create"),
    path("culture/edit/<int:pk>", views.CultureUpdate.as_view(), name="culture_edit"),
    path(
        "culture/delete/<int:pk>", views.CultureDelete.as_view(), name="culture_delete"
    ),
    path("fabric/", views.FabricListView.as_view(), name="fabric_browse"),
    path(
        "fabric/detail/<int:pk>", views.FabricDetailView.as_view(), name="fabric_detail"
    ),
    path("fabric/create/", views.FabricCreate.as_view(), name="fabric_create"),
    path("fabric/edit/<int:pk>", views.FabricUpdate.as_view(), name="fabric_edit"),
    path("fabric/delete/<int:pk>", views.FabricDelete.as_view(), name="fabric_delete"),
    path("hardware/", views.HardwareListView.as_view(), name="hardware_browse"),
    path(
        "hardware/detail/<int:pk>",
        views.HardwareDetailView.as_view(),
        name="hardware_detail",
    ),
    path("hardware/create/", views.HardwareCreate.as_view(), name="hardware_create"),
    path(
        "hardware/edit/<int:pk>", views.HardwareUpdate.as_view(), name="hardware_edit"
    ),
    path(
        "hardware/delete/<int:pk>",
        views.HardwareDelete.as_view(),
        name="hardware_delete",
    ),
    path(
        "illustration/",
        views.IllustrationListView.as_view(),
        name="illustration_browse",
    ),
    path(
        "illustration/detail/<int:pk>",
        views.IllustrationDetailView.as_view(),
        name="illustration_detail",
    ),
    path(
        "illustration/create/",
        views.IllustrationCreate.as_view(),
        name="illustration_create",
    ),
    path(
        "illustration/edit/<int:pk>",
        views.IllustrationUpdate.as_view(),
        name="illustration_edit",
    ),
    path(
        "illustration/delete/<int:pk>",
        views.IllustrationDelete.as_view(),
        name="illustration_delete",
    ),
    path(
        "illustrationpanel/",
        views.IllustrationPanelListView.as_view(),
        name="illustrationpanel_browse",
    ),
    path(
        "illustrationpanel/detail/<int:pk>",
        views.IllustrationPanelDetailView.as_view(),
        name="illustrationpanel_detail",
    ),
    path(
        "illustrationpanel/create/",
        views.IllustrationPanelCreate.as_view(),
        name="illustrationpanel_create",
    ),
    path(
        "illustrationpanel/edit/<int:pk>",
        views.IllustrationPanelUpdate.as_view(),
        name="illustrationpanel_edit",
    ),
    path(
        "illustrationpanel/delete/<int:pk>",
        views.IllustrationPanelDelete.as_view(),
        name="illustrationpanel_delete",
    ),
    path(
        "imagingtechnique/",
        views.ImagingTechniqueListView.as_view(),
        name="imagingtechnique_browse",
    ),
    path(
        "imagingtechnique/detail/<int:pk>",
        views.ImagingTechniqueDetailView.as_view(),
        name="imagingtechnique_detail",
    ),
    path(
        "imagingtechnique/create/",
        views.ImagingTechniqueCreate.as_view(),
        name="imagingtechnique_create",
    ),
    path(
        "imagingtechnique/edit/<int:pk>",
        views.ImagingTechniqueUpdate.as_view(),
        name="imagingtechnique_edit",
    ),
    path(
        "imagingtechnique/delete/<int:pk>",
        views.ImagingTechniqueDelete.as_view(),
        name="imagingtechnique_delete",
    ),
    path(
        "institution/", views.InstitutionListView.as_view(), name="institution_browse"
    ),
    path(
        "institution/detail/<int:pk>",
        views.InstitutionDetailView.as_view(),
        name="institution_detail",
    ),
    path(
        "institution/create/",
        views.InstitutionCreate.as_view(),
        name="institution_create",
    ),
    path(
        "institution/edit/<int:pk>",
        views.InstitutionUpdate.as_view(),
        name="institution_edit",
    ),
    path(
        "institution/delete/<int:pk>",
        views.InstitutionDelete.as_view(),
        name="institution_delete",
    ),
    path("material/", views.MaterialListView.as_view(), name="material_browse"),
    path(
        "material/detail/<int:pk>",
        views.MaterialDetailView.as_view(),
        name="material_detail",
    ),
    path("material/create/", views.MaterialCreate.as_view(), name="material_create"),
    path(
        "material/edit/<int:pk>", views.MaterialUpdate.as_view(), name="material_edit"
    ),
    path(
        "material/delete/<int:pk>",
        views.MaterialDelete.as_view(),
        name="material_delete",
    ),
    path("object/", views.ObjectListView.as_view(), name="object_browse"),
    path(
        "object/detail/<int:pk>", views.ObjectDetailView.as_view(), name="object_detail"
    ),
    path("object/create/", views.ObjectCreate.as_view(), name="object_create"),
    path("object/edit/<int:pk>", views.ObjectUpdate.as_view(), name="object_edit"),
    path("object/delete/<int:pk>", views.ObjectDelete.as_view(), name="object_delete"),
    path(
        "paintingstyle/",
        views.PaintingStyleListView.as_view(),
        name="paintingstyle_browse",
    ),
    path(
        "paintingstyle/detail/<int:pk>",
        views.PaintingStyleDetailView.as_view(),
        name="paintingstyle_detail",
    ),
    path(
        "paintingstyle/create/",
        views.PaintingStyleCreate.as_view(),
        name="paintingstyle_create",
    ),
    path(
        "paintingstyle/edit/<int:pk>",
        views.PaintingStyleUpdate.as_view(),
        name="paintingstyle_edit",
    ),
    path(
        "paintingstyle/delete/<int:pk>",
        views.PaintingStyleDelete.as_view(),
        name="paintingstyle_delete",
    ),
    path(
        "paintingsubtechnique/",
        views.PaintingSubTechniqueListView.as_view(),
        name="paintingsubtechnique_browse",
    ),
    path(
        "paintingsubtechnique/detail/<int:pk>",
        views.PaintingSubTechniqueDetailView.as_view(),
        name="paintingsubtechnique_detail",
    ),
    path(
        "paintingsubtechnique/create/",
        views.PaintingSubTechniqueCreate.as_view(),
        name="paintingsubtechnique_create",
    ),
    path(
        "paintingsubtechnique/edit/<int:pk>",
        views.PaintingSubTechniqueUpdate.as_view(),
        name="paintingsubtechnique_edit",
    ),
    path(
        "paintingsubtechnique/delete/<int:pk>",
        views.PaintingSubTechniqueDelete.as_view(),
        name="paintingsubtechnique_delete",
    ),
    path("period/", views.PeriodListView.as_view(), name="period_browse"),
    path(
        "period/detail/<int:pk>", views.PeriodDetailView.as_view(), name="period_detail"
    ),
    path("period/create/", views.PeriodCreate.as_view(), name="period_create"),
    path("period/edit/<int:pk>", views.PeriodUpdate.as_view(), name="period_edit"),
    path("period/delete/<int:pk>", views.PeriodDelete.as_view(), name="period_delete"),
    path("person/", views.PersonListView.as_view(), name="person_browse"),
    path(
        "person/detail/<int:pk>", views.PersonDetailView.as_view(), name="person_detail"
    ),
    path("person/create/", views.PersonCreate.as_view(), name="person_create"),
    path("person/edit/<int:pk>", views.PersonUpdate.as_view(), name="person_edit"),
    path("person/delete/<int:pk>", views.PersonDelete.as_view(), name="person_delete"),
    path("place/", views.PlaceListView.as_view(), name="place_browse"),
    path("place/detail/<int:pk>", views.PlaceDetailView.as_view(), name="place_detail"),
    path("place/create/", views.PlaceCreate.as_view(), name="place_create"),
    path("place/edit/<int:pk>", views.PlaceUpdate.as_view(), name="place_edit"),
    path("place/delete/<int:pk>", views.PlaceDelete.as_view(), name="place_delete"),
    path("shape/", views.ShapeListView.as_view(), name="shape_browse"),
    path("shape/detail/<int:pk>", views.ShapeDetailView.as_view(), name="shape_detail"),
    path("shape/create/", views.ShapeCreate.as_view(), name="shape_create"),
    path("shape/edit/<int:pk>", views.ShapeUpdate.as_view(), name="shape_edit"),
    path("shape/delete/<int:pk>", views.ShapeDelete.as_view(), name="shape_delete"),
    path(
        "shapecomponent/",
        views.ShapeComponentListView.as_view(),
        name="shapecomponent_browse",
    ),
    path(
        "shapecomponent/detail/<int:pk>",
        views.ShapeComponentDetailView.as_view(),
        name="shapecomponent_detail",
    ),
    path(
        "shapecomponent/create/",
        views.ShapeComponentCreate.as_view(),
        name="shapecomponent_create",
    ),
    path(
        "shapecomponent/edit/<int:pk>",
        views.ShapeComponentUpdate.as_view(),
        name="shapecomponent_edit",
    ),
    path(
        "shapecomponent/delete/<int:pk>",
        views.ShapeComponentDelete.as_view(),
        name="shapecomponent_delete",
    ),
    path("threeddata/", views.ThreedDataListView.as_view(), name="threeddata_browse"),
    path(
        "threeddata/detail/<int:pk>",
        views.ThreedDataDetailView.as_view(),
        name="threeddata_detail",
    ),
    path(
        "threeddata/create/", views.ThreedDataCreate.as_view(), name="threeddata_create"
    ),
    path(
        "threeddata/edit/<int:pk>",
        views.ThreedDataUpdate.as_view(),
        name="threeddata_edit",
    ),
    path(
        "threeddata/delete/<int:pk>",
        views.ThreedDataDelete.as_view(),
        name="threeddata_delete",
    ),
]
