# Generated by Django 6.1.2 on 2026-10-07 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vocabs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certainty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('cert_label', models.CharField(blank=True, max_length=250, verbose_name='Certainty')),
                ('cert_id', models.CharField(blank=True, max_length=250, verbose_name='Certainty, Getty AAT ID')),
            ],
            options={
                'verbose_name': 'Certainty',
                'verbose_name_plural': 'Certainties',
                'ordering': ['cert_label'],
            },
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('culture', models.CharField(blank=True, max_length=250, verbose_name='Culture')),
                ('culture_id', models.CharField(blank=True, max_length=250, verbose_name='Culture, Getty AAT ID')),
            ],
            options={
                'verbose_name': 'Culture',
                'verbose_name_plural': 'Cultures',
                'ordering': ['culture'],
            },
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('material_fabric', models.CharField(blank=True, max_length=250, verbose_name='Material: Fabric')),
                ('material_fabric_id', models.CharField(blank=True, max_length=250, verbose_name='Material: Fabric, Getty AAT ID')),
            ],
            options={
                'verbose_name': 'Fabric',
                'verbose_name_plural': 'Fabrics',
                'ordering': ['material_fabric'],
            },
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('threed_hardware', models.CharField(blank=True, max_length=250, verbose_name="3D Survey: hardware ['hardware' AAT ID: 300312368]")),
            ],
            options={
                'verbose_name': 'Hardware for 3D imaging',
                'verbose_name_plural': 'Hardware for 3D imaging',
                'ordering': ['threed_hardware'],
            },
        ),
        migrations.CreateModel(
            name='ImagingTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('threed_technique', models.CharField(blank=True, max_length=250, verbose_name='3D Survey: imaging technique')),
                ('threed_technique_id', models.CharField(blank=True, max_length=250, verbose_name='3D Survey: imaging technique [AAT ID]')),
            ],
            options={
                'verbose_name': 'Imaging technique',
                'verbose_name_plural': 'Imaging techniques',
                'ordering': ['threed_technique'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('inst_name', models.CharField(blank=True, max_length=250, verbose_name='Institution name')),
                ('inst_geo_id', models.CharField(blank=True, help_text='Collection [institution] [GeoNameID]', max_length=250, verbose_name='Geonames ID of institution')),
                ('inst_id', models.URLField(blank=True, help_text='Preferably from GND, or then VIAF or ORCID', null=True, verbose_name='Identifier of Institution')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
                'ordering': ['inst_name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('material', models.CharField(blank=True, max_length=250, verbose_name='Material')),
                ('material_id', models.CharField(blank=True, max_length=250, verbose_name='Material, Getty AAT ID')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'ordering': ['material'],
            },
        ),
        migrations.CreateModel(
            name='PaintingStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('painting_style', models.CharField(blank=True, max_length=250, verbose_name='Painting style/technique')),
                ('painting_style_id', models.CharField(blank=True, max_length=250, verbose_name='Painting style/technique, Getty AAT ID')),
            ],
            options={
                'verbose_name': 'Painting style / technique',
                'verbose_name_plural': 'Painting styles / techniques',
                'ordering': ['painting_style'],
            },
        ),
        migrations.CreateModel(
            name='PaintingSubTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('painting_style_sub', models.CharField(blank=True, max_length=250, verbose_name='Painting sub technique')),
                ('painting_style_sub_id', models.CharField(blank=True, max_length=250, verbose_name='Painting sub technique, Getty AAT ID')),
            ],
            options={
                'verbose_name': 'Painting sub-technique',
                'verbose_name_plural': 'Painting sub-techniques',
                'ordering': ['painting_style_sub'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('period', models.CharField(blank=True, max_length=250, verbose_name='Period')),
                ('period_abbrev', models.CharField(blank=True, max_length=250, verbose_name='Period, Abbreviation')),
                ('period_id', models.URLField(blank=True, null=True, verbose_name='Period, ID')),
                ('period_dating_start', models.IntegerField(blank=True, null=True, verbose_name='Period dating start')),
                ('period_dating_end', models.IntegerField(blank=True, null=True, verbose_name='Period dating end')),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
                'ordering': ['period_dating_start'],
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('shape', models.CharField(blank=True, max_length=250, verbose_name='Shape')),
                ('shape_alt', models.CharField(blank=True, max_length=250, verbose_name='Shape, alternate names')),
                ('shape_id', models.CharField(blank=True, max_length=250, verbose_name='Shape, Getty AAT ID')),
            ],
            options={
                'verbose_name': 'Shape',
                'verbose_name_plural': 'Shapes',
                'ordering': ['shape'],
            },
        ),
        migrations.CreateModel(
            name='ShapeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('shape_comp', models.CharField(blank=True, max_length=250, verbose_name='Shape components')),
                ('shape_comp_id', models.CharField(blank=True, max_length=250, verbose_name='Shape components, Getty AAT ID')),
            ],
            options={
                'verbose_name': 'Shape component',
                'verbose_name_plural': 'Shape components',
                'ordering': ['shape_comp'],
            },
        ),
        migrations.CreateModel(
            name='CollectionSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('collection_spec', models.CharField(blank=True, help_text='Name of the specific collection the object is part of', max_length=250, verbose_name='Collection, Specific')),
                ('collection_spec_folder', models.CharField(blank=True, help_text='The folder in which objects of this collection are stored', max_length=250, verbose_name='Name of containing folder')),
                ('partof_institution', models.ForeignKey(blank=True, help_text='The institution the specific collection is part of', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_collectionspec_partof_institution_institution', to='vases.institution', verbose_name='Part of Institution')),
            ],
            options={
                'verbose_name': 'Specific collection',
                'verbose_name_plural': 'Specific collections',
                'ordering': ['collection_spec'],
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('folder_name', models.CharField(blank=True, help_text='Name of the folder containing all files related to the object', max_length=250, verbose_name='Folder name')),
                ('inv_nr', models.CharField(blank=True, help_text='Inventory number of object', max_length=250, verbose_name='ID Inv. Nr.')),
                ('bapd_nr', models.CharField(blank=True, help_text='Corresponding number of Beazley Archive Pottery Database', max_length=250, verbose_name='BAPD Nr.')),
                ('object_dating_start', models.IntegerField(blank=True, null=True, verbose_name='Object dating start')),
                ('object_dating_end', models.IntegerField(blank=True, null=True, verbose_name='Object dating end')),
                ('provenance_attribution', models.CharField(blank=True, help_text='Provenance: attributed to artist/maker', max_length=250, verbose_name='Attributed to artist/maker')),
                ('provenance_acquisition_date', models.DateField(blank=True, help_text="Provenance: date of latest acquisition (modern times), based on Getty AAT 'period' (300081446)", null=True, verbose_name='Date of latest acquisition')),
                ('bibref', models.TextField(blank=True, verbose_name='Bibliographic Reference')),
                ('collref', models.URLField(blank=True, null=True, verbose_name='Collection reference')),
                ('weight', models.DecimalField(blank=True, decimal_places=10, help_text='Weight in grams', max_digits=19, null=True, verbose_name='Weight <small>(g)</small>')),
                ('width', models.DecimalField(blank=True, decimal_places=10, help_text='Width in millimetres', max_digits=19, null=True, verbose_name='Width <small>(mm)</small>')),
                ('height', models.DecimalField(blank=True, decimal_places=10, help_text='Height in millimetres', max_digits=19, null=True, verbose_name='Height <small>(mm)</small>')),
                ('length', models.DecimalField(blank=True, decimal_places=10, help_text='Length in millimetres', max_digits=19, null=True, verbose_name='Length <small>(mm)</small>')),
                ('fillingheight', models.DecimalField(blank=True, decimal_places=10, help_text='Maximum filling heigth in millimetres', max_digits=19, null=True, verbose_name='Max. Filling Height <small>(mm)</small>')),
                ('fillingvolume', models.DecimalField(blank=True, decimal_places=10, help_text='Maximum filling volume in cm3', max_digits=19, null=True, verbose_name='Max. Filling Volume <small>(cm3)</small>')),
                ('materialvolume', models.DecimalField(blank=True, decimal_places=10, help_text='Material volume in cm3', max_digits=19, null=True, verbose_name='Material Volume <small>(cm3)</small>')),
                ('materialdensity', models.DecimalField(blank=True, decimal_places=10, help_text='Material density in g/cm3', max_digits=19, null=True, verbose_name='Material Density <small>(g/cm3)</small>')),
                ('materialdensity_measure', models.CharField(blank=True, help_text='Material Density: measured or estimated', max_length=250, verbose_name='Material Density measure')),
                ('boundingbox', models.DecimalField(blank=True, decimal_places=10, help_text='Bounding box in cm3', max_digits=19, null=True, verbose_name='Bounding Box <small>(cm3)</small>')),
                ('object_notes', models.TextField(blank=True, verbose_name='Notes')),
                ('collection_inst', models.ForeignKey(blank=True, help_text='Name of the collection where the object is kept at; as defined by Getty AAT ID: 300025976', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_object_collection_inst_institution', to='vases.institution', verbose_name='Institution')),
                ('collection_spec', models.ForeignKey(blank=True, help_text='Name of the specific collection the object is part of; as defined by Getty AAT ID: 300025976', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_object_collection_spec_collectionspec', to='vases.collectionspec', verbose_name='Collection')),
                ('culture', models.ManyToManyField(blank=True, related_name='rvn_object_culture_culture', to='vases.culture', verbose_name='Culture')),
                ('material', models.ManyToManyField(blank=True, related_name='rvn_object_material_material', to='vases.material', verbose_name='Material')),
                ('material_fabric', models.ManyToManyField(blank=True, help_text='Material: Fabric', related_name='rvn_object_material_fabric_fabric', to='vases.fabric', verbose_name='Fabric (BAPD)')),
                ('object_associated_to_inv', models.ManyToManyField(blank=True, help_text='Object is associated to, ID Inv. Nr.', related_name='rvn_object_object_associated_to_inv_object', to='vases.object', verbose_name='Object is associated to')),
                ('provenance_production_cert', models.ForeignKey(blank=True, help_text='Provenance: Production center, certainty', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_object_provenance_production_cert_certainty', to='vases.certainty', verbose_name='Production center, certainty')),
                ('provenance_spot_cert', models.ForeignKey(blank=True, help_text='Provenance: Finding spot, certainty', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_object_provenance_spot_cert_certainty', to='vases.certainty', verbose_name='Finding spot, certainty')),
                ('painting_style', models.ManyToManyField(blank=True, related_name='rvn_object_painting_style_paintingstyle', to='vases.paintingstyle', verbose_name='Painting style/technique')),
                ('painting_style_sub', models.ManyToManyField(blank=True, related_name='rvn_object_painting_style_sub_paintingsubtechnique', to='vases.paintingsubtechnique', verbose_name='Painting sub technique')),
                ('period', models.ManyToManyField(blank=True, related_name='rvn_object_period_period', to='vases.period', verbose_name='Period')),
            ],
            options={
                'verbose_name': 'Vase',
                'verbose_name_plural': 'Vases',
                'ordering': ['inv_nr'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('person_last_name', models.CharField(blank=True, help_text='Last name of a person', max_length=250, verbose_name='Last Name')),
                ('person_first_name', models.CharField(blank=True, help_text='First name of a person', max_length=250, verbose_name='First Name')),
                ('person_id', models.URLField(blank=True, help_text='Preferably from GND, or then VIAF or ORCID', null=True, verbose_name='Identifier of Person')),
                ('person_member_inst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_person_person_member_inst_institution', to='vases.institution', verbose_name='Member institution of person')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ['person_last_name'],
            },
        ),
        migrations.CreateModel(
            name='IllustrationPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('illtab_file_name', models.CharField(blank=True, help_text='File name of illustration table', max_length=250, verbose_name='File name')),
                ('illtab_date', models.DateField(blank=True, help_text='Illustration date', null=True, verbose_name='Creation date')),
                ('illtab_software', models.CharField(blank=True, help_text='Illustration software', max_length=250, verbose_name='Software')),
                ('illtab_software_steps', models.CharField(blank=True, help_text='Illustration software actions', max_length=250, verbose_name='Software actions')),
                ('illtab_notes', models.TextField(blank=True, verbose_name='Notes')),
                ('folder_name', models.ForeignKey(blank=True, help_text='Folder name of object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_illustrationpanel_folder_name_object', to='vases.object', verbose_name='Folder name')),
                ('illtab_author', models.ManyToManyField(blank=True, help_text='Illustration author', related_name='rvn_illustrationpanel_illtab_author_person', to='vases.person', verbose_name='Creator(s)')),
            ],
            options={
                'verbose_name': 'Illustration table',
                'verbose_name_plural': 'Illustration tables',
                'ordering': ['illtab_file_name'],
            },
        ),
        migrations.CreateModel(
            name='Illustration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('ill_file_name', models.CharField(blank=True, help_text='File name of illustration', max_length=250, verbose_name='File name')),
                ('ill_date', models.DateField(blank=True, help_text='Illustration date', null=True, verbose_name='Creation date')),
                ('ill_software', models.CharField(blank=True, help_text='Illustration software', max_length=250, verbose_name='Software')),
                ('ill_software_steps', models.CharField(blank=True, help_text='Illustration software actions', max_length=250, verbose_name='Software actions')),
                ('ill_notes', models.TextField(blank=True, verbose_name='Notes')),
                ('folder_name', models.ForeignKey(blank=True, help_text='Folder name of object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_illustration_folder_name_object', to='vases.object', verbose_name='Folder name')),
                ('ill_author', models.ManyToManyField(blank=True, help_text='Illustration author', related_name='rvn_illustration_ill_author_person', to='vases.person', verbose_name='Creator(s)')),
            ],
            options={
                'verbose_name': 'Illustration',
                'verbose_name_plural': 'Illustrations',
                'ordering': ['ill_file_name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('place_name', models.CharField(blank=True, max_length=250, verbose_name='Name of place')),
                ('geonames_id', models.URLField(blank=True, null=True, verbose_name='Identifier of place')),
                ('coord_exact', models.BooleanField(blank=True, help_text='Yes, if coordinates are exact.', null=True, verbose_name='Coordinates are exact?')),
                ('lat', models.DecimalField(blank=True, decimal_places=12, help_text='The latitude of the place', max_digits=20, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=12, help_text='The longitude of the place', max_digits=20, null=True)),
                ('place_type', models.ManyToManyField(blank=True, help_text='Type of place in relation to the object. E. g. is it a find place or a production place?', related_name='rvn_place_place_type_skosconcept', to='vocabs.skosconcept', verbose_name='Type of place')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
                'ordering': ['place_name'],
            },
        ),
        migrations.AddField(
            model_name='object',
            name='provenance_acquisition',
            field=models.ManyToManyField(blank=True, help_text='Provenance: place of latest acquisition (modern times)', related_name='rvn_object_provenance_acquisition_place', to='vases.place', verbose_name='Latest acquisition'),
        ),
        migrations.AddField(
            model_name='object',
            name='provenance_production',
            field=models.ForeignKey(blank=True, help_text='Provenance: Production center', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_object_provenance_production_place', to='vases.place', verbose_name='Production center'),
        ),
        migrations.AddField(
            model_name='object',
            name='provenance_spot',
            field=models.ForeignKey(blank=True, help_text='Provenance: Finding spot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_object_provenance_spot_place', to='vases.place', verbose_name='Finding spot'),
        ),
        migrations.AddField(
            model_name='object',
            name='shape',
            field=models.ManyToManyField(blank=True, related_name='rvn_object_shape_shape', to='vases.shape', verbose_name='Shape'),
        ),
        migrations.AddField(
            model_name='object',
            name='shape_comp',
            field=models.ManyToManyField(blank=True, related_name='rvn_object_shape_comp_shapecomponent', to='vases.shapecomponent', verbose_name='Shape components'),
        ),
        migrations.CreateModel(
            name='ThreedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('threed_location_char', models.CharField(blank=True, max_length=250, verbose_name='3D Survey: location characteristics')),
                ('threed_date', models.DateField(blank=True, null=True, verbose_name='3D Survey: date')),
                ('threed_fov', models.CharField(blank=True, max_length=250, verbose_name='FOV')),
                ('threed_resolution', models.CharField(blank=True, max_length=250, verbose_name='Resolution limit [AAT ID: 300222980]')),
                ('threed_acc', models.CharField(blank=True, max_length=250, verbose_name='Feature Accuracy *')),
                ('threed_texture_acquisition', models.CharField(blank=True, choices=[('texture_acq_scanner', 'scanner'), ('texture_acq_3dscanner', '3D scanner'), ('texture_acq_camera', 'external camera')], max_length=250, verbose_name='Image texture acquisition [3D scanner/external camera]')),
                ('threed_texture_color', models.CharField(blank=True, choices=[('texture_color_color', 'colour'), ('texture_color_bw', 'B&W')], max_length=250, verbose_name='Image texture acquisition [colour/B&W]')),
                ('threed_texture_resolution', models.CharField(blank=True, max_length=250, verbose_name='Image texture resolution')),
                ('threed_software', models.CharField(blank=True, max_length=250, verbose_name='Software acquisition')),
                ('threed_scan_nrs', models.IntegerField(blank=True, null=True, verbose_name='Nr. scans')),
                ('threed_merging_date', models.DateField(blank=True, null=True, verbose_name='3D data alignment/merging: date')),
                ('threed_merging_software', models.CharField(blank=True, max_length=250, verbose_name='3D data alignment/merging: software')),
                ('threed_postproc_date', models.DateField(blank=True, null=True, verbose_name='3D merged model post-processing: date')),
                ('threed_postproc_software', models.CharField(blank=True, max_length=250, verbose_name='3D merged model post-processing: software')),
                ('threed_postproc_actions', models.CharField(blank=True, max_length=250, verbose_name='3D merged model post-processing: actions')),
                ('threed_postproc_file', models.CharField(blank=True, max_length=250, verbose_name='3D merged post-processed model: file name')),
                ('threed_postproc_low_date', models.DateField(blank=True, null=True, verbose_name='Low resolution 3D model post-processing: date')),
                ('threed_postproc_low_software', models.CharField(blank=True, max_length=250, verbose_name='Low resolution 3D model post-processing: software')),
                ('threed_postproc_low_software_actions', models.CharField(blank=True, max_length=250, verbose_name='Low resolution 3D model post-processing: actions')),
                ('threed_postproc_low_file', models.CharField(blank=True, max_length=250, verbose_name='Low resolution 3D model: file name')),
                ('threed_notes', models.TextField(blank=True, help_text='Notes [AAT ID: 300027200]', verbose_name='Notes')),
                ('folder_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_threeddata_folder_name_object', to='vases.object', verbose_name='Folder name')),
                ('threed_author', models.ManyToManyField(blank=True, related_name='rvn_threeddata_threed_author_person', to='vases.person', verbose_name='3D Survey: author')),
                ('threed_hardware', models.ForeignKey(blank=True, help_text="3D Survey: hardware ['hardware' AAT ID: 300312368]", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_threeddata_threed_hardware_hardware', to='vases.hardware', verbose_name='Model')),
                ('threed_location', models.ManyToManyField(blank=True, related_name='rvn_threeddata_threed_location_institution', to='vases.institution', verbose_name='3D Survey: location')),
                ('threed_merging_author', models.ManyToManyField(blank=True, related_name='rvn_threeddata_threed_merging_author_person', to='vases.person', verbose_name='3D data alignment/merging: author')),
                ('threed_postproc_author', models.ManyToManyField(blank=True, related_name='rvn_threeddata_threed_postproc_author_person', to='vases.person', verbose_name='3D merged model post-processing: author')),
                ('threed_postproc_low_author', models.ManyToManyField(blank=True, related_name='rvn_threeddata_threed_postproc_low_author_person', to='vases.person', verbose_name='Low resolution 3D model post-processing: author')),
                ('threed_technique', models.ForeignKey(blank=True, help_text='3D Survey: imaging technique', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_threeddata_threed_technique_imagingtechnique', to='vases.imagingtechnique', verbose_name='Type')),
            ],
            options={
                'verbose_name': '3D data',
                'verbose_name_plural': '3D data',
                'ordering': ['folder_name'],
            },
        ),
    ]
